-- MySQL Workbench Synchronization
-- Generated: 2019-06-13 18:21
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Capacitacion18

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE TABLE IF NOT EXISTS `almacenes`.`Almacenes` (
  `CodAlm` INT(11) NOT NULL DEFAULT 'Codigo',
  `LugAlm` VARCHAR(100) NOT NULL DEFAULT 'Lugar',
  `CapaAlm` INT(11) NOT NULL DEFAULT 'Capacidad',
  PRIMARY KEY (`CodAlm`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `almacenes`.`Cajas` (
  `NumRefCajas` CHAR(5) NOT NULL DEFAULT 'Numero Referencia CAjas',
  `ConteCajas` NVARCHAR(100) NOT NULL DEFAULT 'Contenido Cajas',
  `ValCajas` INT(11) NOT NULL DEFAULT Valor,
  `AlmCajas` INT(11) NOT NULL,
  PRIMARY KEY (`NumRefCajas`),
  INDEX `Almacenes_idx` (`AlmCajas` ASC) VISIBLE,
  CONSTRAINT `Almacenes`
    FOREIGN KEY (`AlmCajas`)
    REFERENCES `almacenes`.`Almacenes` (`CodAlm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
